version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
orbs:
  ruby: circleci/ruby@0.1.2 

jobs: # our first job, named "build"
  build:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout # pull down our git code.
      # - ruby/install-deps # use the ruby orb to install dependencies
      - run:
          name: install bundler
          command: gem install bundler        
      - run:
          name: Which bundler?
          command: bundler -v
      - ruby/bundle-install
  test:
    test:
    docker:
      - image: 'cimg/ruby:2.7-node'
      - environment:
          POSTGRES_DB: tweeter_api_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: adam
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: adam
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - run:
          name: test
          command: rspec

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      # - run:
      #     name: Database setup
      #     command: rails db:{create, migrate}
      # - run:
      #     name: test
      #     command: rspec
      # # - ruby/rspec-test